name: Auto-add issues to project board

on:
  issues:
    types: [opened]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@244f685bbc3b7adfa8466e08b698b5577571133e # v1.0.2
        with:
          project-url: https://github.com/users/jb-brown/projects/1
          github-token: ${{ secrets.PROJECT_BOARD_AUTO_ADD }}
